## alpine image lesz amit létrehozok
## csináld meg hogy a dev környezetet egy futásből összerakja, illetve majd a prodot is
version: "3.8"
services:
  # frontend:
  #   image: frontendapp
  #   build:
  #     context: ./frontend
  #     # target: development
  #   environment:
  #     PORT: 3000
  #     PROXY_API: http://nodejsapp:8080/
  #   ports:
  #     - 3000:80
  #   volumes:
  #     #- ./frontend/nginx.conf:/etc/nginx/nginx.conf
  #     - ./frontend/dist:/usr/share/nginx/html
  #   depends_on:
  #     - nodejsapp
  nodejsapp:
    image: nodejsapp ## kell majd ide egy tag később hogy szép legyen
    build:
      context: ./
      target: development ## todo ez majd a prodnál más lesz
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - MONGODB_CONNSTRING=mongodb://mongo:27017/nodejsapp
      - MONGODB_USER=test # TODO set it from a file
      - MONGODB_PASSWORD=test # TODO same as above
      - NODE_ENV=development
      - JWT_SECRET=showcase-portfolio-app-secret-key
      - JWT_EXPIRES_IN=90d
    volumes:
      - ./:/app
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
      - mongodb-config:/data/configdb
volumes:
  mongo-data:
  mongodb-config:
